const ServiceList = [
    {
        bgColor: "bg-accentPositivus",
        bgText: "bg-primaryPositivus",
        textColor: "text-black",
        text1: "Search Engine",
        text2: "Optimization",
        img: "/assets/images/seo.svg",
        arrow: "/assets/icons/arrow-green.svg",
    },
    {
        bgColor: "bg-primaryPositivus",
        bgText: "bg-white",
        textColor: "text-black",
        text1: "Pay-per-click",
        text2: "advertising",
        img: "/assets/images/payper.svg",
        arrow: "/assets/icons/arrow-green.svg",
    },
    {
        bgColor: "bg-darkPositivus",
        bgText: "bg-white",
        textColor: "text-black",
        text1: "Social Media",
        text2: "Management",
        img: "/assets/images/social-media.svg",
        arrow: "/assets/icons/arrow-white.svg",
        moreColor: "text-white",
    },
    {
        bgColor: "bg-accentPositivus",
        bgText: "bg-primaryPositivus",
        textColor: "text-black",
        text1: "Email",
        text2: "Marketing",
        img: "/assets/images/email.svg",
        arrow: "/assets/icons/arrow-green.svg",
    },
    {
        bgColor: "bg-primaryPositivus",
        bgText: "bg-accentPositivus",
        textColor: "text-black",
        text1: "Content",
        text2: "Creation",
        img: "/assets/images/content-creation.svg",
        arrow: "/assets/icons/arrow-green.svg",
    },
    {
        bgColor: "bg-darkPositivus",
        bgText: "bg-white",
        textColor: "text-black",
        text1: "Analytics and ",
        text2: "Tracking",
        moreColor: "text-white",
        img: "/assets/images/analytics.svg",
        arrow: "/assets/icons/arrow-white.svg",
    },
];

export default ServiceList;